config/routes.rb
Rails.application.routes.draw do


  get 'tags/:id'   => 'tags#show', as: 'tag'
  get 'tags'       => 'tags#index'

  resources :posts

  get    'about'   =>  'static_pages#about'
  get    'contact' =>  'static_pages#contact'

  #login and logout routes
  get    'login'   =>  'sessions#new'
  post   'login'   =>  'sessions#create'
  delete 'logout'  =>  'sessions#destroy'

  root 'posts#index'
end

app/models/author.rb
class Author < ActiveRecord::Base

  has_secure_password
  has_many :posts, dependent: :destroy

  VALID_EMAIL_FORMAT= /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates :email,    presence: true, length: { maximum: 50 },
                       format: { with: VALID_EMAIL_FORMAT},
                       uniqueness: {case_sensitive: false}
  validates :name,     presence: true, length: { maximum: 50 }
  validates :password, presence: true, length: { minimum: 6  }

  before_save { self.email = email.downcase }

  # Returns the hash digest of the given string. FOR TEST
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

end

app/models/post.rb
class Post < ActiveRecord::Base

  validates :title, presence: true, length: { maximum: 35 }
  validates :text, presence: true

  belongs_to :author
  has_and_belongs_to_many :tags

  def self.search(search)
    where("text || title ILIKE ?", "%#{search}%")
  end

  def text_limit(number)
    self.text[0..number].gsub(/\s\w+\s*$/,'...')
  end

  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    self.tags.map(&:name).join(", ")
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # TODO - fix this, cant logout this way.
  #protect_from_forgery with: :exception


  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :must_logged,    only: [:new, :create, :edit, :update, :destroy]
  before_action :correct_author, only: [:edit, :update, :destroy]

  def index
    @posts = Post.paginate(page: params[:page], per_page: 10)
                 .order(created_at: :desc)
    if params[:search]
      @posts = Post.search(params[:search]).order(created_at: :desc)
    end
  end

  def new
    @post = current_author.posts.new
  end

  def create
    @post = current_author.posts.new(post_params)
    if @post.save
      redirect_to root_url
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to @post
    else
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_url
  end
  private

    def post_params
      params.require(:post).permit(:title, :text, :all_tags)
    end

    def correct_author
      @post = Post.find_by(id: params[:id])
      redirect_to root_url unless current_author == @post.author
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :must_not_logged, only: [:new, :create]

  def new
  end

  def create
    author = Author.find_by(email: params[:session][:email].downcase)
    if author && author.authenticate(params[:session][:password])
      log_in author
      redirect_to root_url
    else
      flash[:alert] = "Invalid email/password"
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def about
  end

  def contact
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
      @tags = Tag.all
  end

  def show
    @tag = Tag.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  #Logs in the given author
  def log_in(author)
    session[:author_id] = author.id
  end

  #Returns current logged-in author
  def current_author
    @current_author ||= Author.find_by(id: session[:author_id])
  end

  #returns if a author is logged or not
  def logged_in?
    !current_author.nil?
  end

  def log_out
    session.delete(:author_id)
    @current_author = nil
  end

  #is it ugly this 2 methods, isnt?
  def must_logged
    redirect_to root_url unless logged_in?
  end

  def must_not_logged
    redirect_to root_url if logged_in?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Clean Blog</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <%= render "shared/navigation" %>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <%= render "shared/header" %>

    <!-- Main Content -->
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
    <!-- Footer -->
    <%= render "shared/footer" %>

</body>

</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post, html: { class: 'form-horizontal' }) do |f| %>

  <%= f.input :title %>
  <%= f.input :text %>
  <%= f.text_field :all_tags, placeholder: "Put tags with a comma" %> <br>
  <%= f.button :submit %>
<% end %>

app/views/posts/edit.html.erb
<%= render 'form' %>
<%= link_to "Delete post", post_path(@post),
            method: :delete,
            data: { confirm: 'Are you sure?' }%>

app/views/posts/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

            <% @posts.each do |post| %>
              <div class="post-preview">
                <%= link_to post do %>
                      <h2 class="post-title">
                          <%= post.title %>
                      </h2>
                      <h3 class="post-subtitle">
                          <%= post.text_limit(60) %>
                      </h3>
                  <% end %>
                  <p class="post-meta">Posted by <%= post.author.name %> on
                    <%= post.updated_at.to_formatted_s(:short)  %> </p>
              </div>
              <hr>
            <% end %>
            <div class="dickr_pagination text-center">
              <%= will_paginate @posts, page_links: false %>
            </div>
            <!-- Pager
            <ul class="pager">
                <li class="next">
                    <a href="#">Older Posts &rarr;</a>
                </li> -->
            </ul>
        </div>
    </div>
</div>

<hr>

app/views/posts/new.html.erb
<div class="text-center">
  <%= "Logged as: #{current_author.name}" %>

  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<article>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <!-- <blockquote>The dreams of yesterday are the hopes of today
                and the reality of tomorrow. Science has not yet mastered
                prophecy. We predict too much for the next year and yet far
                too little for the next ten.</blockquote> -->

                <%= @post.text %>
                <br>

                <div class="text-center text-muted">
                  tags:
                  <% @post.tags.each do |tag| %>
                    <%= link_to tag.name, tag_path(tag) %>
                  <% end %>
                </div>

                <% if current_author == @post.author %>
                  <%= link_to "Edit", edit_post_path, class: "btn btn-default" %>
                <% end %>
            </div>
        </div>
    </div>
</article>


<hr>

app/views/shared/_footer.html.erb
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <ul class="list-inline text-center">
                    <li>
                        <a href="https://www.twitter.com/carloszansavio">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="https://www.facebook.com/bookdocarlos">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="https://www.github.com/carloszan">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <div class="text-center text-muted">Looking for something?
                  <%= form_tag(posts_path, method: :get, id: "search-form") do %>
                  <%= text_field_tag :search, params[:search], placeholder: "Search something" %>
                  <%= submit_tag "Go" %>
                  <% end %>
                </div>
                <p class="copyright text-muted">Copyright &copy; CleanBlog Bootstrap</p>
            </div>
        </div>
    </div>
</footer>

app/views/shared/_header.html.erb
<header class="intro-header" style="background-image: url(<%= image_path('home-bg.jpg') %>)">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>Clean Blog</h1>
                    <hr class="small">
                    <span class="subheading">A Clean Blog Theme by Start Bootstrap</span>
                </div>
            </div>
        </div>
    </div>
</header>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "Blogzeira do Carlos", root_path, class: "navbar-brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <%= link_to "Home", root_path %>
                </li>
                <li>
                    <%= link_to "About", about_path %>
                </li>
                <li>
                  <%= link_to "Contact", contact_path %>
                </li>
                <% if logged_in? %>
                <li>
                    <%= link_to "Create a post", new_post_path %>
                </li>
                <li>
                    <%= link_to "Log out", logout_path, method: "delete" %>
                </li>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/static_pages/about.html.erb
<div class="text-center">
  I am Carlos, a computer scientist student from Viçosa, MG - Brasil
</div>

app/views/static_pages/contact.html.erb
<div class="text-center">
  There's no way from contact me right now :D
</div>

app/views/tags/index.html.erb
<% @tags.each do |tag| %>
  <%= link_to tag.name, tag_path(tag) %><br>
<% end %>

app/views/tags/show.html.erb
<div class="text-center">
  <% @tag.posts.each do |post| %>
    <%= link_to post.title, post %> <br>
  <% end %>
</div>